### ISSUE TITLE
Double-check all line numbers

### ISSUE THREAD

**Issue by nkronenfeld** [nkronenfeld/RenDance#1]

**Comment by Puzzle88Piecer** [comment]
First 3 dances were done before we had a standardized method, so especially need checking.

**Comment by Puzzle88Piecer** [comment]
Sue has now gone through the first 5 dances.  Ippiter (the one where the problem was first noted) had several minor numbering problems (mostly, only referred to one line number, when the text spanned more than one line).  Most, if not all, of the rest were perfect.  Suspending this task unless and until evidence resurfaces that other dances are having these problems.
